# Generated by Django 4.2.26 on 2026-02-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('optimal_temp_min', models.FloatField(help_text='Minimum optimal temperature in Celsius')),
                ('optimal_temp_max', models.FloatField(help_text='Maximum optimal temperature in Celsius')),
                ('water_requirement', models.CharField(help_text='e.g., High, Medium, Low', max_length=100)),
                ('soil_type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
            ],
        ),
    ]
