# Generated by Django 4.2.27 on 2026-02-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='fertilizers',
            field=models.TextField(blank=True, default='Balanced NPK 10:10:10', help_text='Recommended fertilizers'),
        ),
        migrations.AddField(
            model_name='crop',
            name='manures',
            field=models.TextField(blank=True, default='Farm Yard Manure', help_text='Recommended manures'),
        ),
        migrations.AddField(
            model_name='crop',
            name='pesticides',
            field=models.TextField(blank=True, default='Neem Oil', help_text='Recommended pesticides'),
        ),
    ]
