# Generated by Django 4.2.27 on 2026-02-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_crop_fertilizers_crop_manures_crop_pesticides'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='harvested_date',
            field=models.DateField(blank=True, help_text='Expected or actual harvest date', null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='is_tracked',
            field=models.BooleanField(default=False, help_text='Show this crop on the dashboard for daily tracking'),
        ),
        migrations.AddField(
            model_name='crop',
            name='planted_date',
            field=models.DateField(blank=True, help_text='Date when the crop was planted', null=True),
        ),
    ]
